#!/usr/bin/env bash
# Emit e2e output index (fixed path, fixed order). No existence checks.
set -euo pipefail

OUT="/tmp/anchor_e2e_index_last.out"

{
  echo "MODULE=anchor_e2e_index"
  echo "TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "RELEASE_OUT=/tmp/anchor_e2e_release_up_and_verify_last.out"
  echo "VERIFY_ALL_OUT=/tmp/anchor_e2e_verify_all_release.out"
  echo "CHECKLIST_RETRY_OUT=/tmp/anchor_e2e_checklist_retry_e2e_last.out"
  echo "CHECKLIST_EVENTS_OUT=/tmp/anchor_e2e_checklist_events_e2e_last.out"
  echo "CHECKLIST_QUOTE_OUT=/tmp/anchor_e2e_checklist_quote_e2e_last.out"
  echo "CHECKLIST_LIST_RETRY_UI_OUT=/tmp/anchor_e2e_checklist_list_retry_ui_e2e_last.out"
  echo "CHECKLIST_CREATE_FORM_UI_OUT=/tmp/anchor_e2e_checklist_create_form_ui_e2e_last.out"
  echo "CHECKLIST_CREATE_NAV_EVENTS_OUT=/tmp/anchor_e2e_checklist_create_navigate_events_e2e_last.out"
  echo "CHECKLIST_DETAIL_EXPLAINER_OUT=/tmp/anchor_e2e_checklist_detail_explainer_e2e_last.out"
  echo "CHECKLIST_POLICY_BLOCK_EXPLAINER_OUT=/tmp/anchor_e2e_checklist_policy_block_explainer_e2e_last.out"
  echo "CHECKLIST_CREATE_PAYLOAD_SCHEMA_UI_OUT=/tmp/anchor_e2e_checklist_create_payload_schema_ui_e2e_last.out"
  echo "CHECKLIST_KILL_SWITCH_OUT=/tmp/anchor_e2e_checklist_kill_switch_e2e_last.out"
  echo "CHECKLIST_WORKER_HEARTBEAT_OUT=/tmp/anchor_e2e_checklist_worker_heartbeat_e2e_last.out"
  echo "CHECKLIST_KILL_SWITCH_REDIS_OUT=/tmp/anchor_e2e_checklist_kill_switch_redis_e2e_last.out"
  echo "CHECKLIST_OPS_CONSOLE_OUT=/tmp/anchor_e2e_checklist_ops_console_e2e_last.out"
  echo "CHECKLIST_OPS_SUMMARY_OUT=/tmp/anchor_e2e_checklist_ops_summary_e2e_last.out"
  echo "CHECKLIST_WORKER_PANIC_GUARD_OUT=/tmp/anchor_e2e_checklist_worker_panic_guard_e2e_last.out"
  echo "CHECKLIST_OPS_STATE_OUT=/tmp/anchor_e2e_checklist_ops_state_e2e_last.out"
  echo "CHECKLIST_OPS_DASHBOARD_UI_OUT=/tmp/anchor_e2e_checklist_ops_dashboard_ui_e2e_last.out"
  echo "CHECKLIST_RISK_PANEL_UI_OUT=/tmp/anchor_e2e_checklist_risk_panel_ui_e2e_last.out"
  echo "CHECKLIST_RISK_LOCKOUT_BLOCK_OUT=/tmp/anchor_e2e_checklist_risk_lockout_block_e2e_last.out"
  echo "CHECKLIST_RISK_HARD_LIMITS_OUT=/tmp/anchor_e2e_checklist_risk_hard_limits_e2e_last.out"
  echo "CHECKLIST_EXTREME_MODE_E2E_OUT=/tmp/anchor_e2e_checklist_extreme_mode_e2e_last.out"
  echo "ops_dashboard_ui_e2e"
  echo "risk_panel_ui_e2e"
  echo "risk_lockout_block_e2e"
  echo "risk_hard_limits_e2e"
  echo "extreme_mode_e2e"
} > "$OUT"
