CREATE TABLE IF NOT EXISTS ops_audit (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor TEXT NOT NULL DEFAULT 'system',
  action TEXT NOT NULL,
  detail JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE ops_audit
  ADD COLUMN IF NOT EXISTS ts TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE ops_audit
  ADD COLUMN IF NOT EXISTS actor TEXT NOT NULL DEFAULT 'system';
ALTER TABLE ops_audit
  ADD COLUMN IF NOT EXISTS action TEXT NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE ops_audit
  ADD COLUMN IF NOT EXISTS detail JSONB NOT NULL DEFAULT '{}'::jsonb;
